githubtest/apps/book/urls.py
from django.urls import path
from .views import IndexView, ListView, DetailView

urlpatterns = [
    path('index', IndexView.as_view(), name='index'),
    path('list/<int:page>', ListView.as_view(), name='list'),
    path('list', ListView.as_view(), name='list1'),
    path('detail/<int:book_id>', DetailView.as_view(), name='detail'),
    path('', IndexView.as_view(), name='index'),
]

githubtest/ebooklevel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('apps.user.urls', 'apps.user'), namespace='user')),
    path('book/', include(('apps.book.urls', 'apps.book'), namespace='book')),
    #path('', include(('apps.book.urls', 'apps.user'), namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

githubtest/templates/book_list.html
{# ref: show-list.html #}
{% extends 'base.html' %}
{% load static %}
{% block title %}book list{% endblock title %}
{% block slider %}{% endblock %}
{% block body %}

        <!-- Start Shop Page -->
        <div class="page-shop-sidebar left--sidebar bg--white section-padding--lg">
        	<div class="container">
        		<div class="row">
        			<div class="col-lg-3 col-12 order-2 order-lg-1 md-mt-40 sm-mt-40">
        				<div class="shop__sidebar">
        					<aside class="wedget__categories poroduct--cat">
        						<h3 class="wedget__title">Product Categories</h3>
        						<ul>
        							<li><a href="#">Biography <span>(3)</span></a></li>
        							<li><a href="#">Business <span>(4)</span></a></li>
        							<li><a href="#">Cookbooks <span>(6)</span></a></li>
        							<li><a href="#">Health & Fitness <span>(7)</span></a></li>
        							<li><a href="#">History <span>(8)</span></a></li>
        							<li><a href="#">Mystery <span>(9)</span></a></li>
        							<li><a href="#">Inspiration <span>(13)</span></a></li>
        							<li><a href="#">Romance <span>(20)</span></a></li>
        							<li><a href="#">Fiction/Fantasy <span>(22)</span></a></li>
        							<li><a href="#">Self-Improvement <span>(13)</span></a></li>
        							<li><a href="#">Humor Books <span>(17)</span></a></li>
        							<li><a href="#">Harry Potter <span>(20)</span></a></li>
        							<li><a href="#">Land of Stories <span>(34)</span></a></li>
        							<li><a href="#">Kids' Music <span>(60)</span></a></li>
        							<li><a href="#">Toys & Games <span>(3)</span></a></li>
        							<li><a href="#">hoodies <span>(3)</span></a></li>
        						</ul>
        					</aside>
        					<aside class="wedget__categories pro--range">
        						<h3 class="wedget__title">Filter by price</h3>
        						<div class="content-shopby">
        						    <div class="price_filter s-filter clear">
        						        <form action="#" method="GET">
        						            <div id="slider-range"></div>
        						            <div class="slider__range--output">
        						                <div class="price__output--wrap">
        						                    <div class="price--output">
        						                        <span>Price :</span><input type="text" id="amount" readonly="">
        						                    </div>
        						                    <div class="price--filter">
        						                        <a href="#">Filter</a>
        						                    </div>
        						                </div>
        						            </div>
        						        </form>
        						    </div>
        						</div>
        					</aside>
        					<aside class="wedget__categories poroduct--compare">
        						<h3 class="wedget__title">Compare</h3>
        						<ul>
        							<li><a href="#">x</a><a href="#">Condimentum posuere</a></li>
        							<li><a href="#">x</a><a href="#">Condimentum posuere</a></li>
        							<li><a href="#">x</a><a href="#">Dignissim venenatis</a></li>
        						</ul>
        					</aside>
        					<aside class="wedget__categories poroduct--tag">
        						<h3 class="wedget__title">Product Tags</h3>
        						<ul>
        							<li><a href="#">Biography</a></li>
        							<li><a href="#">Business</a></li>
        							<li><a href="#">Cookbooks</a></li>
        							<li><a href="#">Health & Fitness</a></li>
        							<li><a href="#">History</a></li>
        							<li><a href="#">Mystery</a></li>
        							<li><a href="#">Inspiration</a></li>
        							<li><a href="#">Religion</a></li>
        							<li><a href="#">Fiction</a></li>
        							<li><a href="#">Fantasy</a></li>
        							<li><a href="#">Music</a></li>
        							<li><a href="#">Toys</a></li>
        							<li><a href="#">Hoodies</a></li>
        						</ul>
        					</aside>
        					<aside class="wedget__categories sidebar--banner">
								<img src="{% static 'images/others/banner_left.jpg' %}" alt="banner images">
								<div class="text">
									<h2>new products</h2>
									<h6>save up to <br> <strong>40%</strong>off</h6>
								</div>
        					</aside>
        				</div>
        			</div>
        			<div class="col-lg-9 col-12 order-1 order-lg-2">
        				<div class="row">
        					<div class="col-lg-12">
								<div class="shop__list__wrapper d-flex flex-wrap flex-md-nowrap justify-content-between">
									<div class="shop__list nav justify-content-center" role="tablist">
			                            <a class="nav-item nav-link" data-toggle="tab" href="#nav-grid" role="tab"><i class="fa fa-th"></i></a>
			                            <a class="nav-item nav-link active" data-toggle="tab" href="#nav-list" role="tab"><i class="fa fa-list"></i></a>
			                        </div>
			                        <p>Showing 1–12 of 40 results</p>
			                        <div class="orderby__wrapper">
			                        	<span>Sort By</span>
			                        	<select class="shot__byselect" onchange="self.location.href=options[selectedIndex].value">
			                        		<option {% if sort == 'default' %} selected="selected" {% endif %} value = "{% url 'book:list' '1' %}?sort=default">Default sorting</option>
			                        		<option {% if sort == 'price' %} selected="selected" {% endif %} value = "{% url 'book:list' '1' %}?sort=price">Price</option>
                                            <option {% if sort == 'douban_score' %} selected="selected" {% endif %} value="{% url 'book:list' '1' %}?sort=douban_score">Douban_score</option>
			                        	</select>
			                        </div>
		                        </div>
        					</div>
        				</div>
        				<div class="tab__container">
	        				<div class="shop-grid tab-pane fade show active" id="nav-list" role="tabpanel">
	        					<div class="list__view__wrapper">
                                    {% for book in page_obj %}
                                        <!-- Start Single Product -->
                                        <div class="list__view">
                                            <div class="thumb">
                                                <a class="first__img" href="{% url 'book:detail' book.id %}"><img src="{{ book.cover_img.url }}" alt="product images"></a>
{#                                                <a class="second__img animation1" href="single-product.html"><img src="images/product/2.jpg" alt="product images"></a>#}
                                            </div>
                                            <div class="content">
                                                <h2><a href="{% url 'book:detail' book.id %}">{{ book.title }}</a></h2>

                                                <table border="1">
                                                    <tr>
                                                        <th>难度：{{ book.words_hard_level }}</th>
                                                        <th>评分：{{ book.douban_score }}</th>
                                                        <th>适合年龄：</th>
                                                    </tr>
                                                </table>
                                                <p>作者：{{ book.author_name_str_cn }}</p>
                                                <ul class="prize__box">
                                                    <li>{{ book.price }}</li>
                                                    <li class="old__prize">$220.00</li>
                                                </ul>
                                                     <ul class="rating d-flex">
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li><i class="fa fa-star-o"></i></li>
                                                    <li><i class="fa fa-star-o"></i></li> {{ book.douban_score }}({{ book.douban_score_num }}人评论)
                                                </ul>
                                                <p>现在人内心流失的东西，这家杂货店帮你找回-僻静的街道旁有一家杂货店，只要写下烦恼，投进家门口的投信口，第二天就会得到回答。</p>
                                                <p>
                                                    <a href="javascripte:;">想读</a>
                                                    <a href="javascripte:;">在读</a>
                                                    <a href="javascripte:;">读过</a>
                                                </p>
                                                <p>
                                                    <a href="javascripte:;">在豆瓣购买</a>
                                                    <a href="javascripte:;">加入购书单</a>
                                                </p>


{#                                                <p>{{ book.subtitle }};{{ book.douban_series_id }};{{ book.publisher_name }}</p>#}
                                                <ul class="cart__action d-flex">
                                                    <li class="cart"><a href="cart.html">Add to cart</a></li>
                                                    <li class="wishlist"><a href="cart.html"></a></li>
                                                    <li class="compare"><a href="cart.html"></a></li>
                                                </ul>

                                            </div>
                                        </div>
                                        <br/>{# 列表项之间 空行#}
                                        <!-- End Single Product -->
                                    {% endfor %}
	        					</div>
                                <ul class="wn__pagination">
                                    {% if page_obj.has_previous %}
                                        <li><a href="{% url 'book:list' page_obj.previous_page_number %}?sort={{ sort }}"><i class="zmdi zmdi-chevron-left"></i></a></li>
                                    {% endif %}
                                    {% for pindex in pages %}
                                        {% if pindex == page_obj.number %}
                                            <li class="active"><a href="{% url 'book:list' pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a></li>
                                        {% else %}
                                            <li><a href="{% url 'book:list' pindex %}?sort={{ sort }}">{{ pindex }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li><a href="{% url 'book:list' page_obj.next_page_number %}?sort={{ sort }}"><i class="zmdi zmdi-chevron-right"></i></a></li>
                                    {% endif %}
                                </ul>
	        				</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </div>
        <!-- End Shop Page -->
{% endblock body %}

githubtest/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}index{% endblock title %}
{% block slider %}{% endblock slider %}
{% block body %}
{#    todo footer 到了顶部#}
{% endblock body %}

githubtest/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}login{% endblock title %}
{% block slider %}{% endblock %}
{% block body %}
    <!-- Start My Account Area -->
    <section class="my_account_area pt--80 pb--55 bg--white">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-12">
                </div>
                <div class="col-lg-6 col-12">
                    <div class="my__account__wrapper">
                        <h3 class="account__title">Login</h3>
                        <form method="post">
                            <div class="account__form">
                                <div class="input__box">
                                    <label>Username or email address <span>*</span></label>
                                    <input type="text" name="username" value="{{ username }}" placeholder="请输入用户名">
                                </div>
                                <div class="input__box">
                                    <label>Password<span>*</span></label>
                                    <input type="password" name="password" placeholder="请输入密码">
                                </div>
                                <div class="form__btn">
                                    <button>Login</button>
                                    <label class="label-for-checkbox">
                                        <input id="rememberme" class="input-checkbox" name="rememberme"
                                               type="checkbox" {{ checked }}>
                                        <span>Remember me</span>
                                    </label>
                                </div>
                                <a class="forget_pass" href="#">Lost your password?</a>
                            </div>
                        </form>
                        {{ errmsg }}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End My Account Area -->
{% endblock body %}

githubtest/templates/register.html
{# ref: my-acount.html#}
{% extends 'base.html' %}
{% load static %}
{% block title %}register{% endblock title %}
{% block slider %}{% endblock slider%}
{% block body %}
    <!-- Start My Account Area -->
    <section class="my_account_area pt--80 pb--55 bg--white">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-12">
                </div>
                <div class="col-lg-4 col-12">
                    <div class="my__account__wrapper">
                        <h3 class="account__title">Register</h3>
{# todo form  validate #}
                        <form method="post" action="/user/register">
                            <div class="account__form">
                                <div class="input__box">
                                    <label>username<span>*</span></label>
                                    <input type="text" name="user_name" placeholder="用户名" required="required"
                                           pattern="^[\u2E80-\u9FFF\w-]{4,20}$" autofocus="autofocus">
                                </div>
                                <div class="input__box">
                                    <label>Password<span>*</span></label>
                                    <input type="password" name="password" placeholder="密码" required="required">
                                </div>
                                <div class="input__box">
                                    <label>confirm Password<span>*</span></label>
                                    <input type="password" placeholder="确认密码" required="required">
                                </div>
                                <div class="input__box">
                                    <label>Email address <span>*</span></label>
                                    <input type="email" name="email" placeholder="邮箱" required="required">
                                </div>
                                <label>注册即代表同意《todo协议》《隐私保护指引》</label>
                                <span class="error_tip2"></span>
                                <div class="form__btn">
                                    <button>Register</button>
                                </div>
                            </div>
                        </form>
                        {{ errmsg }}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End My Account Area -->
{% endblock %}